// Generated by CoffeeScript 1.3.3

window.addEventListener("load", function() {
  var app, resetButton, savePatternButton, toggleShowHint, unlockButton;
  app = new LockScreen({
    container: "lock-screen",
    width: 400,
    height: 400,
    onSuccess: function() {
      return console.log("Pattern successed");
    },
    onFailure: function() {
      return console.log("Pattern unmatched");
    },
    pattern: "1-2-3-4-5-6-7-8-9"
  });
  unlockButton = document.getElementById("unlock-button");
  savePatternButton = document.getElementById("save-pattern-button");
  resetButton = document.getElementById("reset-button");
  toggleShowHint = true;
  savePatternButton.addEventListener("click", (function() {
    var span;
    span = this.getElementsByClassName("gray");
    if (span.className === "red") {
      this.innerHTML = "<span class='gray'></span>Record Pattern";
      span.className = "gray";
      app.stopRecordPattern();
      unlockButton.style.display = "inline";
      resetButton.style.display = "inline";
    } else {
      this.innerHTML = "<span class='red'></span>Recording...";
      span.className = "red";
      app.startRecordPattern();
      unlockButton.style.display = "none";
      resetButton.style.display = "none";
    }
    return true;
  }), false);
  unlockButton.addEventListener("click", (function() {
    var _this = this;
    if (app.unlock() !== false) {
      this.className = "button green";
      alert("Access Granted!");
    } else {
      this.className = "button red";
      setTimeout((function() {
        _this.className = "button blue";
        app.clear();
        return true;
      }), 1000);
    }
    return true;
  }), false);
  resetButton.addEventListener("click", (function() {
    app.reset();
    unlockButton.className = "button blue";
    return true;
  }), false);
  document.addEventListener("keyup", (function(e) {
    if ((e.keyCode || e.which) === 72) {
      app.showHint(toggleShowHint);
      toggleShowHint = !toggleShowHint;
    }
    return true;
  }));
  return true;
});
